name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên branch `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0  # Chọn version Node phù hợp với dự án

      - name: Install dependencies
        run: npm install

      - name: Setup environment variables
        run: echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" > .env

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # Deploy lên branch `gh-pages`
          folder: dist  # Thư mục build của Vite
